// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ddc.proto

package native_ddc_sdk_platform

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Role int32

const (
	Role_OPERATOR         Role = 0
	Role_PLATFORM_MANAGER Role = 1
	Role_CONSUMER         Role = 2
)

var Role_name = map[int32]string{
	0: "OPERATOR",
	1: "PLATFORM_MANAGER",
	2: "CONSUMER",
}

var Role_value = map[string]int32{
	"OPERATOR":         0,
	"PLATFORM_MANAGER": 1,
	"CONSUMER":         2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{0}
}

type State int32

const (
	State_FROZEN State = 0
	State_ACTIVE State = 1
)

var State_name = map[int32]string{
	0: "FROZEN",
	1: "ACTIVE",
}

var State_value = map[string]int32{
	"FROZEN": 0,
	"ACTIVE": 1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{1}
}

type Function int32

const (
	Function_MINT            Function = 0
	Function_EDIT            Function = 1
	Function_BURN            Function = 2
	Function_TRANSFER        Function = 3
	Function_DDC_APPROVE     Function = 4
	Function_ACCOUNT_APPROVE Function = 5
	Function_FREEZE          Function = 6
	Function_UNFREEZE        Function = 7
	Function_BATCH_BURN      Function = 8
	Function_BATCH_TRANSFER  Function = 9
)

var Function_name = map[int32]string{
	0: "MINT",
	1: "EDIT",
	2: "BURN",
	3: "TRANSFER",
	4: "DDC_APPROVE",
	5: "ACCOUNT_APPROVE",
	6: "FREEZE",
	7: "UNFREEZE",
	8: "BATCH_BURN",
	9: "BATCH_TRANSFER",
}

var Function_value = map[string]int32{
	"MINT":            0,
	"EDIT":            1,
	"BURN":            2,
	"TRANSFER":        3,
	"DDC_APPROVE":     4,
	"ACCOUNT_APPROVE": 5,
	"FREEZE":          6,
	"UNFREEZE":        7,
	"BATCH_BURN":      8,
	"BATCH_TRANSFER":  9,
}

func (x Function) String() string {
	return proto.EnumName(Function_name, int32(x))
}

func (Function) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{2}
}

type Protocol int32

const (
	Protocol_NFT Protocol = 0
	Protocol_MT  Protocol = 1
)

var Protocol_name = map[int32]string{
	0: "NFT",
	1: "MT",
}

var Protocol_value = map[string]int32{
	"NFT": 0,
	"MT":  1,
}

func (x Protocol) String() string {
	return proto.EnumName(Protocol_name, int32(x))
}

func (Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{3}
}

type DDC struct {
	Protocol Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=bianjieai.ddc.Protocol" json:"protocol,omitempty"`
	Denom    string   `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *DDC) Reset()         { *m = DDC{} }
func (m *DDC) String() string { return proto.CompactTextString(m) }
func (*DDC) ProtoMessage()    {}
func (*DDC) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{0}
}
func (m *DDC) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DDC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DDC.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DDC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DDC.Merge(m, src)
}
func (m *DDC) XXX_Size() int {
	return m.Size()
}
func (m *DDC) XXX_DiscardUnknown() {
	xxx_messageInfo_DDC.DiscardUnknown(m)
}

var xxx_messageInfo_DDC proto.InternalMessageInfo

type AccountInfo struct {
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	DID           string `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role          Role   `protobuf:"varint,4,opt,name=role,proto3,enum=bianjieai.ddc.Role" json:"role,omitempty"`
	LeaderDID     string `protobuf:"bytes,5,opt,name=leader_did,json=leaderDid,proto3" json:"leader_did,omitempty"`
	PlatformState State  `protobuf:"varint,6,opt,name=platform_state,json=platformState,proto3,enum=bianjieai.ddc.State" json:"platform_state,omitempty"`
	OperatorState State  `protobuf:"varint,7,opt,name=operator_state,json=operatorState,proto3,enum=bianjieai.ddc.State" json:"operator_state,omitempty"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{1}
}
func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return m.Size()
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

type FeeRule struct {
	Function Function `protobuf:"varint,1,opt,name=function,proto3,enum=bianjieai.ddc.Function" json:"function,omitempty"`
	Fee      uint64   `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *FeeRule) Reset()         { *m = FeeRule{} }
func (m *FeeRule) String() string { return proto.CompactTextString(m) }
func (*FeeRule) ProtoMessage()    {}
func (*FeeRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{2}
}
func (m *FeeRule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeRule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRule.Merge(m, src)
}
func (m *FeeRule) XXX_Size() int {
	return m.Size()
}
func (m *FeeRule) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRule.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRule proto.InternalMessageInfo

type Balance struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_a17c0d613bbf1247, []int{3}
}
func (m *Balance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return m.Size()
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("bianjieai.ddc.Role", Role_name, Role_value)
	proto.RegisterEnum("bianjieai.ddc.State", State_name, State_value)
	proto.RegisterEnum("bianjieai.ddc.Function", Function_name, Function_value)
	proto.RegisterEnum("bianjieai.ddc.Protocol", Protocol_name, Protocol_value)
	proto.RegisterType((*DDC)(nil), "bianjieai.ddc.DDC")
	proto.RegisterType((*AccountInfo)(nil), "bianjieai.ddc.AccountInfo")
	proto.RegisterType((*FeeRule)(nil), "bianjieai.ddc.FeeRule")
	proto.RegisterType((*Balance)(nil), "bianjieai.ddc.Balance")
}

func init() { proto.RegisterFile("ddc.proto", fileDescriptor_a17c0d613bbf1247) }

var fileDescriptor_a17c0d613bbf1247 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xda, 0x4a,
	0x14, 0xb5, 0xf9, 0x34, 0x37, 0x2f, 0x64, 0x34, 0x41, 0xef, 0xf1, 0xde, 0x93, 0x4c, 0xc4, 0xa6,
	0x11, 0x6a, 0x40, 0x6a, 0x16, 0xad, 0xda, 0x95, 0xb1, 0x4d, 0x8b, 0x14, 0x6c, 0x34, 0x31, 0x59,
	0xb0, 0x41, 0x8e, 0x67, 0xa0, 0x6e, 0x8d, 0x27, 0x32, 0xa6, 0xbf, 0xa1, 0xcb, 0xae, 0xbb, 0xca,
	0xae, 0x7f, 0x25, 0xcb, 0x2c, 0xbb, 0x8a, 0x5a, 0xb2, 0xe9, 0xcf, 0xa8, 0x66, 0x8c, 0xa9, 0x1a,
	0xa9, 0xd9, 0x9d, 0x73, 0xef, 0x39, 0xe7, 0x8e, 0xef, 0x8c, 0xa1, 0x46, 0x69, 0xd0, 0xbd, 0x4a,
	0x78, 0xca, 0xf1, 0xfe, 0x65, 0xe8, 0xc7, 0xef, 0x42, 0xe6, 0x87, 0x5d, 0x4a, 0x83, 0xff, 0x1a,
	0x0b, 0xbe, 0xe0, 0xb2, 0xd3, 0x13, 0x28, 0x13, 0xb5, 0xc7, 0x50, 0xb4, 0x2c, 0x13, 0x9f, 0x82,
	0x26, 0x79, 0xc0, 0xa3, 0xa6, 0x7a, 0xa4, 0x1e, 0xd7, 0x9f, 0xfd, 0xd3, 0xfd, 0xcd, 0xde, 0x1d,
	0x6f, 0xdb, 0x64, 0x27, 0xc4, 0x0d, 0x28, 0x53, 0x16, 0xf3, 0x65, 0xb3, 0x70, 0xa4, 0x1e, 0xd7,
	0x48, 0x46, 0xda, 0x5f, 0x0a, 0xb0, 0x67, 0x04, 0x01, 0x5f, 0xc7, 0xe9, 0x30, 0x9e, 0x73, 0xdc,
	0x84, 0xaa, 0x4f, 0x69, 0xc2, 0x56, 0x2b, 0x99, 0x5c, 0x23, 0x39, 0xc5, 0xff, 0x42, 0x91, 0x86,
	0x34, 0x73, 0xf7, 0xab, 0x9b, 0xbb, 0x56, 0xd1, 0x1a, 0x5a, 0x44, 0xd4, 0x30, 0x86, 0x52, 0xec,
	0x2f, 0x59, 0xb3, 0x28, 0x1d, 0x12, 0xe3, 0x27, 0x50, 0x4a, 0x78, 0xc4, 0x9a, 0x25, 0x79, 0xbe,
	0xc3, 0x07, 0xe7, 0x23, 0x3c, 0x62, 0x44, 0x0a, 0xf0, 0x53, 0x80, 0x88, 0xf9, 0x94, 0x25, 0x33,
	0x11, 0x5f, 0x96, 0xf1, 0xfb, 0x9b, 0xbb, 0x56, 0xed, 0x4c, 0x56, 0xc5, 0x90, 0x5a, 0x26, 0xb0,
	0x42, 0x8a, 0x5f, 0x41, 0xfd, 0x2a, 0xf2, 0xd3, 0x39, 0x4f, 0x96, 0xb3, 0x55, 0xea, 0xa7, 0xac,
	0x59, 0x91, 0x03, 0x1a, 0x0f, 0x06, 0x9c, 0x8b, 0x1e, 0xd9, 0xcf, 0xb5, 0x92, 0x0a, 0x33, 0xbf,
	0x62, 0x89, 0x9f, 0xf2, 0x64, 0x6b, 0xae, 0x3e, 0x66, 0xce, 0xb5, 0x92, 0xb6, 0xa7, 0x50, 0x1d,
	0x30, 0x46, 0xd6, 0x11, 0x13, 0xfb, 0x9f, 0xaf, 0xe3, 0x20, 0x0d, 0x79, 0xfc, 0x87, 0xfd, 0x0f,
	0xb6, 0x6d, 0xb2, 0x13, 0x62, 0x04, 0xc5, 0x39, 0x63, 0x72, 0x7f, 0x25, 0x22, 0xe0, 0x4b, 0xed,
	0xe3, 0x75, 0x4b, 0xf9, 0x71, 0xdd, 0x52, 0xda, 0x36, 0x54, 0xfb, 0x7e, 0xe4, 0xc7, 0x01, 0x7b,
	0xe4, 0x02, 0xfe, 0x86, 0x8a, 0xbf, 0x14, 0x17, 0xb5, 0xcd, 0xd8, 0xb2, 0x5f, 0x31, 0x9d, 0x17,
	0x50, 0x12, 0x8b, 0xc5, 0x7f, 0x81, 0xe6, 0x8e, 0x6d, 0x62, 0x78, 0x2e, 0x41, 0x0a, 0x6e, 0x00,
	0x1a, 0x9f, 0x19, 0xde, 0xc0, 0x25, 0xa3, 0xd9, 0xc8, 0x70, 0x8c, 0xd7, 0x36, 0x41, 0xaa, 0xd0,
	0x98, 0xae, 0x73, 0x3e, 0x19, 0xd9, 0x04, 0x15, 0x3a, 0x2d, 0x28, 0x67, 0x2b, 0x02, 0xa8, 0x0c,
	0x88, 0x3b, 0xb5, 0x1d, 0xa4, 0x08, 0x6c, 0x98, 0xde, 0xf0, 0xc2, 0x46, 0x6a, 0xe7, 0xb3, 0x0a,
	0x5a, 0xfe, 0x51, 0x58, 0x83, 0xd2, 0x68, 0xe8, 0x78, 0x48, 0x11, 0xc8, 0xb6, 0x86, 0x1e, 0x52,
	0x05, 0xea, 0x4f, 0x88, 0x83, 0x0a, 0x22, 0xd9, 0x23, 0x86, 0x73, 0x3e, 0xb0, 0x09, 0x2a, 0xe2,
	0x03, 0xd8, 0xb3, 0x2c, 0x73, 0x66, 0x8c, 0xc7, 0xc4, 0xbd, 0xb0, 0x51, 0x09, 0x1f, 0xc2, 0x81,
	0x61, 0x9a, 0xee, 0xc4, 0xf1, 0x76, 0xc5, 0x72, 0x36, 0xd6, 0xb6, 0xa7, 0x36, 0xaa, 0x08, 0xff,
	0xc4, 0xd9, 0xb2, 0x2a, 0xae, 0x03, 0xf4, 0x0d, 0xcf, 0x7c, 0x33, 0x93, 0xe9, 0x1a, 0xc6, 0x50,
	0xcf, 0xf8, 0x6e, 0x46, 0xad, 0xf3, 0x3f, 0x68, 0xf9, 0x83, 0xc7, 0x55, 0x28, 0x3a, 0x03, 0x71,
	0xb4, 0x0a, 0x14, 0x46, 0x1e, 0x52, 0xfb, 0x93, 0x9b, 0xef, 0xba, 0x72, 0xb3, 0xd1, 0xd5, 0xdb,
	0x8d, 0xae, 0x7e, 0xdb, 0xe8, 0xea, 0xa7, 0x7b, 0x5d, 0xb9, 0xbd, 0xd7, 0x95, 0xaf, 0xf7, 0xba,
	0x32, 0x7d, 0xbe, 0x08, 0xd3, 0xb7, 0xeb, 0xcb, 0x6e, 0xc0, 0x97, 0xbd, 0xdd, 0x15, 0xf6, 0x28,
	0x0d, 0x4e, 0x56, 0xf4, 0xfd, 0xc9, 0x82, 0xf7, 0x62, 0x3f, 0x0d, 0x3f, 0xb0, 0x93, 0xbc, 0x92,
	0x3f, 0xa8, 0xcb, 0x8a, 0xfc, 0xb1, 0x4e, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x22, 0xb9, 0x0f,
	0xce, 0xc3, 0x03, 0x00, 0x00,
}

func (m *DDC) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DDC) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DDC) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Protocol != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.Protocol))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AccountInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OperatorState != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.OperatorState))
		i--
		dAtA[i] = 0x38
	}
	if m.PlatformState != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.PlatformState))
		i--
		dAtA[i] = 0x30
	}
	if len(m.LeaderDID) > 0 {
		i -= len(m.LeaderDID)
		copy(dAtA[i:], m.LeaderDID)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.LeaderDID)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Role != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DID) > 0 {
		i -= len(m.DID)
		copy(dAtA[i:], m.DID)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.DID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeeRule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeRule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeRule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fee != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.Fee))
		i--
		dAtA[i] = 0x10
	}
	if m.Function != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.Function))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Balance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Balance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Balance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintDdc(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintDdc(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDdc(dAtA []byte, offset int, v uint64) int {
	offset -= sovDdc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DDC) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Protocol != 0 {
		n += 1 + sovDdc(uint64(m.Protocol))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	return n
}

func (m *AccountInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	l = len(m.DID)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovDdc(uint64(m.Role))
	}
	l = len(m.LeaderDID)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	if m.PlatformState != 0 {
		n += 1 + sovDdc(uint64(m.PlatformState))
	}
	if m.OperatorState != 0 {
		n += 1 + sovDdc(uint64(m.OperatorState))
	}
	return n
}

func (m *FeeRule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Function != 0 {
		n += 1 + sovDdc(uint64(m.Function))
	}
	if m.Fee != 0 {
		n += 1 + sovDdc(uint64(m.Fee))
	}
	return n
}

func (m *Balance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovDdc(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovDdc(uint64(m.Amount))
	}
	return n
}

func sovDdc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDdc(x uint64) (n int) {
	return sovDdc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DDC) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDdc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DDC: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DDC: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			m.Protocol = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Protocol |= Protocol(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDdc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDdc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDdc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= Role(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LeaderDID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LeaderDID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformState", wireType)
			}
			m.PlatformState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlatformState |= State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorState", wireType)
			}
			m.OperatorState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OperatorState |= State(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDdc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDdc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeRule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDdc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeRule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeRule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Function", wireType)
			}
			m.Function = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Function |= Function(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			m.Fee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDdc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDdc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Balance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDdc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Balance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Balance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDdc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDdc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDdc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDdc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDdc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDdc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDdc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDdc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDdc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDdc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDdc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDdc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDdc = fmt.Errorf("proto: unexpected end of group")
)
