// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: token/query.proto

package token

import (
	context "context"
	fmt "fmt"
	native_ddc_sdk_platform "github.com/bianjieai/ddc-sdk-go/native-ddc-sdk-platform"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryBalanceOfRequest is the request type for the Query/BalanceOf RPC method.
type QueryApprovedForAllRequest struct {
	Protocol native_ddc_sdk_platform.Protocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=bianjieai.ddc.Protocol" json:"protocol,omitempty"`
	Denom    string                           `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Owner    string                           `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryApprovedForAllRequest) Reset()         { *m = QueryApprovedForAllRequest{} }
func (m *QueryApprovedForAllRequest) String() string { return proto.CompactTextString(m) }
func (*QueryApprovedForAllRequest) ProtoMessage()    {}
func (*QueryApprovedForAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec043bcd18c4056e, []int{0}
}
func (m *QueryApprovedForAllRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryApprovedForAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryApprovedForAllRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryApprovedForAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryApprovedForAllRequest.Merge(m, src)
}
func (m *QueryApprovedForAllRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryApprovedForAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryApprovedForAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryApprovedForAllRequest proto.InternalMessageInfo

// QueryBalanceOfResponse is the request type for the Query/BalanceOf RPC
// method.
type QueryApprovedForAllResponse struct {
	Operator []string `protobuf:"bytes,1,rep,name=operator,proto3" json:"operator,omitempty"`
}

func (m *QueryApprovedForAllResponse) Reset()         { *m = QueryApprovedForAllResponse{} }
func (m *QueryApprovedForAllResponse) String() string { return proto.CompactTextString(m) }
func (*QueryApprovedForAllResponse) ProtoMessage()    {}
func (*QueryApprovedForAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec043bcd18c4056e, []int{1}
}
func (m *QueryApprovedForAllResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryApprovedForAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryApprovedForAllResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryApprovedForAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryApprovedForAllResponse.Merge(m, src)
}
func (m *QueryApprovedForAllResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryApprovedForAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryApprovedForAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryApprovedForAllResponse proto.InternalMessageInfo

// QueryTokenApprovedRequest is the request type for the Query/TokenApproved RPC
// method.
type QueryTokenApprovedRequest struct {
	Denom   string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	TokenId string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (m *QueryTokenApprovedRequest) Reset()         { *m = QueryTokenApprovedRequest{} }
func (m *QueryTokenApprovedRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokenApprovedRequest) ProtoMessage()    {}
func (*QueryTokenApprovedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec043bcd18c4056e, []int{2}
}
func (m *QueryTokenApprovedRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenApprovedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenApprovedRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenApprovedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenApprovedRequest.Merge(m, src)
}
func (m *QueryTokenApprovedRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenApprovedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenApprovedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenApprovedRequest proto.InternalMessageInfo

// QueryTokenApprovedResponse is the request type for the Query/TokenApproved
// RPC method.
type QueryTokenApprovedResponse struct {
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (m *QueryTokenApprovedResponse) Reset()         { *m = QueryTokenApprovedResponse{} }
func (m *QueryTokenApprovedResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokenApprovedResponse) ProtoMessage()    {}
func (*QueryTokenApprovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec043bcd18c4056e, []int{3}
}
func (m *QueryTokenApprovedResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenApprovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenApprovedResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenApprovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenApprovedResponse.Merge(m, src)
}
func (m *QueryTokenApprovedResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenApprovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenApprovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenApprovedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryApprovedForAllRequest)(nil), "bianjieai.ddc.token.QueryApprovedForAllRequest")
	proto.RegisterType((*QueryApprovedForAllResponse)(nil), "bianjieai.ddc.token.QueryApprovedForAllResponse")
	proto.RegisterType((*QueryTokenApprovedRequest)(nil), "bianjieai.ddc.token.QueryTokenApprovedRequest")
	proto.RegisterType((*QueryTokenApprovedResponse)(nil), "bianjieai.ddc.token.QueryTokenApprovedResponse")
}

func init() { proto.RegisterFile("token/query.proto", fileDescriptor_ec043bcd18c4056e) }

var fileDescriptor_ec043bcd18c4056e = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0x77, 0x52, 0xaa, 0xc9, 0x80, 0x05, 0xc7, 0x82, 0xe9, 0x2a, 0xdb, 0x90, 0x53, 0x10,
	0x33, 0x53, 0x52, 0xf0, 0x20, 0x78, 0x68, 0x05, 0xc1, 0x9b, 0x06, 0x51, 0xf0, 0x22, 0x93, 0x9d,
	0x71, 0x1d, 0xbb, 0x99, 0x77, 0x3b, 0x3b, 0xa9, 0x48, 0xc8, 0xc5, 0x8b, 0x1e, 0x05, 0xbf, 0x40,
	0x0f, 0xde, 0xfc, 0x22, 0x1e, 0x0b, 0x5e, 0x3c, 0x78, 0x90, 0xc4, 0x83, 0x1f, 0x43, 0x76, 0xf6,
	0x8f, 0x9b, 0xb2, 0x85, 0xde, 0xf6, 0x9d, 0x79, 0xe6, 0x79, 0x7f, 0xef, 0xf3, 0x2e, 0xbe, 0x6e,
	0xe1, 0x48, 0x6a, 0x76, 0x3c, 0x93, 0xe6, 0x3d, 0x4d, 0x0c, 0x58, 0x20, 0x37, 0x26, 0x8a, 0xeb,
	0xb7, 0x4a, 0x72, 0x45, 0x85, 0x08, 0xa9, 0x13, 0xf8, 0xdb, 0x11, 0x44, 0xe0, 0xee, 0x59, 0xf6,
	0x95, 0x4b, 0xfd, 0xdb, 0x11, 0x40, 0x14, 0x4b, 0xc6, 0x13, 0xc5, 0xb8, 0xd6, 0x60, 0xb9, 0x55,
	0xa0, 0xd3, 0xe2, 0xb6, 0x93, 0x3d, 0x77, 0x9f, 0xfd, 0x8f, 0x08, 0xfb, 0x4f, 0xb3, 0x1e, 0x07,
	0x49, 0x62, 0xe0, 0x44, 0x8a, 0x47, 0x60, 0x0e, 0xe2, 0x78, 0x2c, 0x8f, 0x67, 0x32, 0xb5, 0x64,
	0x1f, 0xb7, 0x9d, 0x2e, 0x84, 0xb8, 0x8b, 0x7a, 0x68, 0xb0, 0x35, 0xba, 0x49, 0xd7, 0x29, 0x9e,
	0x14, 0xd7, 0xe3, 0x4a, 0x48, 0xb6, 0xf1, 0xa6, 0x90, 0x1a, 0xa6, 0xdd, 0x56, 0x0f, 0x0d, 0x3a,
	0xe3, 0xbc, 0xc8, 0x4e, 0xe1, 0x9d, 0x96, 0xa6, 0xbb, 0x91, 0x9f, 0xba, 0xe2, 0x7e, 0xfb, 0xd3,
	0xe9, 0xae, 0xf7, 0xf7, 0x74, 0xd7, 0xeb, 0x3f, 0xc4, 0xb7, 0x1a, 0x41, 0xd2, 0x04, 0x74, 0x2a,
	0x89, 0x8f, 0xdb, 0x90, 0x48, 0xc3, 0x2d, 0x98, 0x2e, 0xea, 0x6d, 0x0c, 0x3a, 0xe3, 0xaa, 0xae,
	0x99, 0x3c, 0xc7, 0x3b, 0xce, 0xe4, 0x59, 0x96, 0x4d, 0xe9, 0x54, 0x0e, 0x53, 0x71, 0xa1, 0x3a,
	0xd7, 0x0e, 0x6e, 0xbb, 0x24, 0x5f, 0x29, 0x51, 0x00, 0x5f, 0x75, 0xf5, 0x63, 0x51, 0xf3, 0x3d,
	0x2c, 0x52, 0x3a, 0xe7, 0xdb, 0xc8, 0x86, 0x9a, 0xd9, 0x46, 0xbf, 0x5a, 0x78, 0xd3, 0x99, 0x90,
	0x6f, 0x08, 0x6f, 0xad, 0x8f, 0x49, 0x18, 0x6d, 0x58, 0x2e, 0xbd, 0x78, 0x33, 0xfe, 0xde, 0xe5,
	0x1f, 0xe4, 0x94, 0xfd, 0x7b, 0x1f, 0x7e, 0xfc, 0xf9, 0xd2, 0xda, 0x23, 0x94, 0x09, 0x11, 0xb2,
	0xfc, 0xf7, 0xe2, 0x85, 0x94, 0xcd, 0xcb, 0xed, 0x2d, 0xd8, 0xdc, 0xe5, 0xb2, 0x60, 0x73, 0xb7,
	0xa1, 0x05, 0xf9, 0x8a, 0xf0, 0xb5, 0xb5, 0xb9, 0x09, 0xbd, 0xb8, 0x77, 0x53, 0xf0, 0x3e, 0xbb,
	0xb4, 0xbe, 0x40, 0x1d, 0x39, 0xd4, 0xbb, 0xe4, 0x4e, 0x0d, 0x55, 0x88, 0x70, 0xf8, 0x1f, 0xb7,
	0x64, 0x2c, 0x57, 0xb7, 0x38, 0x7c, 0xf1, 0x7d, 0x19, 0xa0, 0xb3, 0x65, 0x80, 0x7e, 0x2f, 0x03,
	0xf4, 0x79, 0x15, 0x78, 0x67, 0xab, 0xc0, 0xfb, 0xb9, 0x0a, 0xbc, 0x97, 0x0f, 0x22, 0x65, 0xdf,
	0xcc, 0x26, 0x34, 0x84, 0x29, 0xab, 0x40, 0x9c, 0x5f, 0x2a, 0x8e, 0x86, 0x11, 0x30, 0xcd, 0xad,
	0x3a, 0x91, 0xc3, 0xf2, 0x24, 0x89, 0xb9, 0x7d, 0x0d, 0x66, 0x9a, 0x37, 0x9e, 0x5c, 0x71, 0xd1,
	0xec, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x31, 0x2f, 0xc4, 0x64, 0x92, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ApprovedForAll queries all the account approved.
	ApprovedForAll(ctx context.Context, in *QueryApprovedForAllRequest, opts ...grpc.CallOption) (*QueryApprovedForAllResponse, error)
	// TokenApproved queries the spender of the token.
	TokenApproved(ctx context.Context, in *QueryTokenApprovedRequest, opts ...grpc.CallOption) (*QueryTokenApprovedResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ApprovedForAll(ctx context.Context, in *QueryApprovedForAllRequest, opts ...grpc.CallOption) (*QueryApprovedForAllResponse, error) {
	out := new(QueryApprovedForAllResponse)
	err := c.cc.Invoke(ctx, "/bianjieai.ddc.token.Query/ApprovedForAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokenApproved(ctx context.Context, in *QueryTokenApprovedRequest, opts ...grpc.CallOption) (*QueryTokenApprovedResponse, error) {
	out := new(QueryTokenApprovedResponse)
	err := c.cc.Invoke(ctx, "/bianjieai.ddc.token.Query/TokenApproved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ApprovedForAll queries all the account approved.
	ApprovedForAll(context.Context, *QueryApprovedForAllRequest) (*QueryApprovedForAllResponse, error)
	// TokenApproved queries the spender of the token.
	TokenApproved(context.Context, *QueryTokenApprovedRequest) (*QueryTokenApprovedResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ApprovedForAll(ctx context.Context, req *QueryApprovedForAllRequest) (*QueryApprovedForAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApprovedForAll not implemented")
}
func (*UnimplementedQueryServer) TokenApproved(ctx context.Context, req *QueryTokenApprovedRequest) (*QueryTokenApprovedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenApproved not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ApprovedForAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApprovedForAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApprovedForAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bianjieai.ddc.token.Query/ApprovedForAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApprovedForAll(ctx, req.(*QueryApprovedForAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokenApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokenApprovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bianjieai.ddc.token.Query/TokenApproved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenApproved(ctx, req.(*QueryTokenApprovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bianjieai.ddc.token.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApprovedForAll",
			Handler:    _Query_ApprovedForAll_Handler,
		},
		{
			MethodName: "TokenApproved",
			Handler:    _Query_TokenApproved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token/query.proto",
}

func (m *QueryApprovedForAllRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryApprovedForAllRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryApprovedForAllRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if m.Protocol != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Protocol))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryApprovedForAllResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryApprovedForAllResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryApprovedForAllResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Operator) > 0 {
		for iNdEx := len(m.Operator) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Operator[iNdEx])
			copy(dAtA[i:], m.Operator[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Operator[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenApprovedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenApprovedRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenApprovedRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TokenId) > 0 {
		i -= len(m.TokenId)
		copy(dAtA[i:], m.TokenId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TokenId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenApprovedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenApprovedResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenApprovedResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryApprovedForAllRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Protocol != 0 {
		n += 1 + sovQuery(uint64(m.Protocol))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryApprovedForAllResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Operator) > 0 {
		for _, s := range m.Operator {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryTokenApprovedRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TokenId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenApprovedResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryApprovedForAllRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryApprovedForAllRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryApprovedForAllRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Protocol", wireType)
			}
			m.Protocol = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Protocol |= native_ddc_sdk_platform.Protocol(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryApprovedForAllResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryApprovedForAllResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryApprovedForAllResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = append(m.Operator, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenApprovedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenApprovedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenApprovedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenApprovedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenApprovedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenApprovedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
