name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Lint operator
      run: |
        cd ./ddc-sdk-operator-go/
        
    - name: ls
      run: ls
    
        
    - name: Set up Lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true

          
  build:
    needs: golangci-lint
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: |
        cd ./ddc-sdk-operator-go/
        go build -v ./app/client.go
        cd ../ddc-sdk-platform-go/
        go build -v ./app/client.go
        
#     - name: Test
#       run: |
#         cd ../ddc-sdk-operator-go/
#         go test ./test
#         cd ../ddc-sdk-platform-go/
#         go test ./test


