name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./ddc-sdk-operator-go/...
           go build -v ./ddc-sdk-platform-go/...


    - name: Test
      run: go test -v ./ddc-sdk-operator-go/...
           go test -v ./ddc-sdk-platform-go/...
