name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-build :
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Lint evm-ddc-sdk-operator
      uses: golangci/golangci-lint-action@v3.1.0
      with:
          working-directory: evm-ddc-sdk-operator
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
          
    - name: Lint evm-ddc-sdk-platform
      uses: golangci/golangci-lint-action@v3.1.0
      with:
          working-directory: evm-ddc-sdk-platform
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
          
#   build:
#     needs: golangci-lint
#     runs-on: ubuntu-lastest
#     steps:
#     - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build evm-ddc-sdk-operator
      working-directory: evm-ddc-sdk-operator
      run: go build -v ./app/client.go
      
    - name: Build evm-ddc-sdk-platform
      working-directory: evm-ddc-sdk-platform
      run: go build -v ./app/client.go
        
#     - name: Test
#       run: |
#         cd ../evm-ddc-sdk-operator/
#         go test ./test
#         cd ../evm-ddc-sdk-platform/
#         go test ./test


